const { readGrammar, cyk } = require('./cyk.js')

function main()
{
  if (process.argv.length !== 4)
  {
    console.log('Usage: node cyk.js <grammar_file> <string>')
    return
  }

  const grammarFile = process.argv[2]
  const string = process.argv[3]

  const grammar = readGrammar(grammarFile)
  const result = cyk(grammar, string)

  if (result)
  {
    console.log(`The string "${string}" can be generated by the grammar.`)
  } else
  {
    console.log(`The string "${string}" cannot be generated by the grammar.`)
  }
}

main();